version: '3'
services:
  postgres:
    image: postgres
    container_name: BerkutTest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=data
